// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoungManGomoku_WebServer.Data;

namespace YoungManGomoku_WebServer.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", b =>
                {
                    b.Property<decimal>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("DisconnectCount")
                        .HasColumnType("bigint");

                    b.Property<long>("DrawCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LoseCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WinCount")
                        .HasColumnType("bigint");

                    b.HasKey("UID");

                    b.ToTable("PlayerGomokuRecordTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerProfile", b =>
                {
                    b.Property<decimal>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("AuthLevel")
                        .HasColumnType("int");

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CashMoney")
                        .HasColumnType("int");

                    b.Property<int>("EquipBoardSkin")
                        .HasColumnType("int");

                    b.Property<int>("EquipProfile")
                        .HasColumnType("int");

                    b.Property<int>("EquipStoneSkin")
                        .HasColumnType("int");

                    b.Property<int>("ExperiencePoint")
                        .HasColumnType("int");

                    b.Property<int>("GameMoney")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxExperiencePoint")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UID");

                    b.ToTable("PlayerProfileTable");
                });
#pragma warning restore 612, 618
        }
    }
}
