// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoungManGomoku_WebServer.Data;

namespace YoungManGomoku_WebServer.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", b =>
                {
                    b.Property<ulong>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("AuthLevel")
                        .HasColumnType("int");

                    b.Property<string>("AuthToken")
                        .HasColumnType("varchar(190) CHARACTER SET utf8mb4")
                        .HasMaxLength(190);

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UID");

                    b.HasIndex("AuthToken")
                        .IsUnique();

                    b.ToTable("PlayerAccountTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", b =>
                {
                    b.Property<ulong>("UID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("DisconnectCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("DrawCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LoseCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("WinCount")
                        .HasColumnType("int unsigned");

                    b.HasKey("UID");

                    b.ToTable("PlayerGomokuBattleRecordTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", b =>
                {
                    b.Property<ulong>("UID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("EquipBoardSkin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("EquipProfile")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("EquipStoneSkin")
                        .HasColumnType("int unsigned");

                    b.HasKey("UID");

                    b.ToTable("PlayerEquipItemStateTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerInventoryItem", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ItemType")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("UID")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("InventoryId");

                    b.HasIndex("UID", "ItemType", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventoryTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", b =>
                {
                    b.Property<ulong>("UID")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("CashMoney")
                        .HasColumnType("int");

                    b.Property<int>("GameMoney")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.ToTable("PlayerMoneyTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", b =>
                {
                    b.Property<ulong>("UID")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ExperiencePoint")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxExperiencePoint")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.HasKey("UID");

                    b.ToTable("PlayerStatusTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("GomokuBattleRecord")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Equip")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerInventoryItem", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithMany("Inventory")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Money")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Status")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
