// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoungManGomoku_WebServer.Data;

namespace YoungManGomoku_WebServer.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", b =>
                {
                    b.Property<decimal>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("AuthLevel")
                        .HasColumnType("int");

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(190)")
                        .HasMaxLength(190);

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UID");

                    b.HasIndex("AuthToken")
                        .IsUnique()
                        .HasFilter("[AuthToken] IS NOT NULL");

                    b.ToTable("PlayerAccountTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", b =>
                {
                    b.Property<decimal>("UID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("DisconnectCount")
                        .HasColumnType("bigint");

                    b.Property<long>("DrawCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LoseCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WinCount")
                        .HasColumnType("bigint");

                    b.HasKey("UID");

                    b.ToTable("PlayerGomokuBattleRecordTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", b =>
                {
                    b.Property<decimal>("UID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("EquipBoardSkin")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipProfile")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipStoneSkin")
                        .HasColumnType("bigint");

                    b.HasKey("UID");

                    b.ToTable("PlayerEquipItemStateTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerInventoryItem", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemType")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("InventoryId");

                    b.HasIndex("UID", "ItemType", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventoryTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", b =>
                {
                    b.Property<decimal>("UID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("CashMoney")
                        .HasColumnType("int");

                    b.Property<int>("GameMoney")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.ToTable("PlayerMoneyTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", b =>
                {
                    b.Property<decimal>("UID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ExperiencePoint")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxExperiencePoint")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("UID");

                    b.ToTable("PlayerStatusTable");
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("GomokuBattleRecord")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerBattleRecord", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Equip")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerEquip", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerInventoryItem", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithMany("Inventory")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Money")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerMoney", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", b =>
                {
                    b.HasOne("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerAccount", "Account")
                        .WithOne("Status")
                        .HasForeignKey("YoungManGomoku_WebServer.Data.DatabaseContext.PlayerStatus", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
